import html from "eslint-plugin-html";

export default [
    {
        files: ["**/*.html"],
        plugins: { html },
    },
    {
        files: ["**/*.js", "**/*.html"],
        languageOptions: {
            ecmaVersion: 2020,
            sourceType: "script",
            globals: {
                window: "readonly",
                document: "readonly",
                localStorage: "readonly",
                console: "readonly",
                fetch: "readonly",
                echarts: "readonly",
                FormData: "readonly",
                XMLHttpRequest: "readonly",
                setTimeout: "readonly",
                setInterval: "readonly",
                clearInterval: "readonly",
                location: "readonly",
                history: "readonly",
                EventSource: "readonly",
                URLSearchParams: "readonly",
                Math: "readonly",
                Date: "readonly",
                navigator: "readonly",
                alert: "readonly",
                confirm: "readonly",
                requestAnimationFrame: "readonly",
                TextDecoder: "readonly",
                Blob: "readonly",
                URL: "readonly",
                toggleTheme: "readonly",
                initThemeIcon: "readonly",
                renderSafeMarkdown: "readonly",
            },
        },
        rules: {
            "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^expect$" }],
            "no-undef": "error",
            "no-dupe-keys": "error",
            "no-empty": ["warn", { "allowEmptyCatch": true }],
            "no-extra-semi": "warn",
            "no-irregular-whitespace": "error",
            "no-unreachable": "error",
            "no-sparse-arrays": "error",
            "use-isnan": "error",
            "valid-typeof": "error",
        },
    },
];
